modLoader = "javafml"
loaderVersion = "[32,)"
license="GNU GPL v3"

[[mods]]
modId = "coloredthings"
version = "${file.jarVersion}"
displayName = "Colored Things"
logoFile = "coloredthings.png"
authors = "Razzokk"
description = '''Colored things add varios colored components to Minecraft e.g: Lamps, Flowers/Crops, dusts and so on'''

[[dependencies.coloredthings]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.coloredthings]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"
